sudo: required
services:
  - docker
before_install:
  - docker pull yshalsager/lineageos:14.1
before_script:
  - cd $HOME && mkdir twrp && PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - cd $HOME/twrp/
  - git config --global color.ui false 
  - repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
  - repo sync
script:
  - cd $HOME/twrp/ && git clone   https://github.com/umamahesh619ra/device_asus_X00R_5.git device/asus/x00r_5
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/twrp/:rw,z" yshalsager/lineageos:14.1 bash << EOF
    cd /home/twrp/
    export ALLOW_MISSING_DEPENDENCIES=true
    source build/envsetup.sh && lunch omni_x00r_5-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/x00r_5/recovery.img $HOME/twrp/TWRP-$version-x00r_5-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key:  "$github_key"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: umamahesh619ra/KernalScript
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
